### PR TITLE
Clean up code and fix template

### PR DESCRIPTION
**Pull request by mdoryammilwalrus**

### CODE REVIEW

**Comment by MotorTruck1221** [comment]
Thanks for contributing! I do have a few things, 
#1 could you make it so the license file isn't modified?
#2 Please switch from yarn to NPM as that's what it uses

**Review by MotorTruck1221 — CHANGES_REQUESTED** [review]
See Previous Comment

**Comment by MotorTruck1221** [comment]
@mdoryammilwalrus

**Comment by mdoryammilwalrus** [comment]
Ok, changed license back to the text version.

Also renamed the file to <span title="Text">txt</span> instead of <span title="Markdown">md</span>

**Comment by mdoryammilwalrus** [comment]
Plus, its not that hard to install yarn
```sh
corepack enable
corepack prepare yarn@stable --activate
```
(corepack comes with nodejs along with npm)

**Comment by mdoryammilwalrus** [comment]
@MotorTruck1221

**Comment by MotorTruck1221** [comment]
> Plus, its not that hard to install yarn
> 
> ```shell
> corepack enable
> corepack prepare yarn@stable --activate
> ```
> 
> (corepack comes with nodejs along with npm)

I know it's not that hard but the CI we use uses NPM and so does the Documentation

**Comment by MotorTruck1221** [comment]
> > Plus, its not that hard to install yarn
> > ```shell
> > corepack enable
> > corepack prepare yarn@stable --activate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (corepack comes with nodejs along with npm)
> 
> I know it's not that hard but the CI we use uses NPM and so does the Documentation

It's not that big of an issue though and i'll switch it

**Review by MotorTruck1221 — APPROVED** [review]
This is great! Merging now

**Pull request merged**
